// import g from "./utilities.mjs";
// import { add, subtract } from "./utilities.mjs";
// console.log(add(2, 3));
// console.log(subtract(2, 3));
// import greet, { subtract, add } from "./utilities.mjs";
// console.log(greet("barsh"));
// console.log(add(2, 3));
// console.log(subtract(2, 3));
import * as utils from "./utilities.mjs";
console.log(utils.add(10, 15));
